### ISSUE TITLE
Is this functional?

### ISSUE THREAD

**Issue by chrisstraight** [jacopocolo/stamp-artboards-name#1]
I've been looking for a plugin like this. Did you get this to work? Nothing appears when I choose '1. Add Artboard Name'. Am I doing something wrong?

Thank you!

**Comment by jacopocolo** [comment]
Hi @chrisstraight, the plugin wasn’t functional but I updated the code and now it works again with Sketch 40.3. Try it out!

**Comment by chrisstraight** [comment]
Thank you for the update and your work on this.

I still can't get anything to appear when I try to add the name. Nothing happens. I downloaded the latest repo and installed it. Restarted Sketch. Any ideas on why it doesn't work?

Also, I'm on Sketch 41 (35326).

**Comment by jacopocolo** [comment]
What happened is this: Sketch got updated and the code I was using broke. It should be an easy fix, however. I’ll take a look and post an update!

**Comment by jacopocolo** [comment]
Done! I quickly tested with 41.1 and it seems to be working!

**Comment by chrisstraight** [comment]
Thank you! This is perfect!
